create table rooms
(
    id   bigint generated by default as identity primary key,
    name varchar
);

create table users
(
    id           bigint generated by default as identity primary key,
    name         varchar,
    password     varchar
);

create table messages
(
    id       bigint generated by default as identity primary key,
    user_id  bigint references users (id) on delete set null,
    room_id  bigint references rooms (id) on delete set null,
    text     varchar,
    datetime timestamp
);

create table last_visited_rooms
(
    user_id  bigint references users (id) on delete cascade ,
    room_id  bigint references rooms (id) on delete set null
);

